---
title: "Exploring the Changing Trends: An Analysis of Non-Response Rates and Impact of telephone Surveys on Survey Methodologies"
author: "Bolin Shen"
date: "February 3, 2024"
date-format: "long" 
format: pdf
thanks: "this analysis is available at: https://github.com/Brian031205/Exploring-the-Changing-Trend"
---
The Special Virtual Issue on “Nonresponse Rates and Nonresponse Adjustments” in the Journal of Survey Statistics and Methodology discusses the challenges posed by declining response rates in surveys, particularly in the context of changing data collection methods. The three selected papers, Williams and Brick (2018), Dutwin and Buskirk (2020), and Daikeler, Bošnjak, and Lozar Manfreda (2020), collectively emphasize the consistent decline in response rates across various survey modes, with a notable impact and influence of the increasing prevalence of telephone surveys. 
Williams and Brick (2018) provide an exploration of nonresponse trends in face-to-face household surveys in the United States, focusing on developments since 2000. In contrast to the predominant attention given to telephone surveys, this research directs towards face-to-face methodologies, which have been comparatively not emphasized in recent studies. The paper specifically examines the aspect of nonresponse, revealing both an overall upward trend and intermittent periods of stability. The study fills a research gap by investigating face-to-face survey nonresponse, presenting a detailed overview covering surveys conducted by government, private, and academic organizations. By analyzing the relative roles of refusals and noncontacts in total nonresponse, the authors provide a better understanding of the contributing factors. The insightful aspect is the exploration of the connection between nonresponse trends and the level of effort invested in surveys. The findings suggest that additional effort taken in the survey may have been consequential in forestalling further declines in face-to-face survey response rates. This paper not only addresses the historical trends but also lays the groundwork for future investigations, emphasizing the importance of understanding the influence of response rates in face-to-face surveys.
Dutwin and Buskirk (2020) undertake thorough assessment of bias inherent in data derived from contemporary telephone interviewing, addressing the prevalent challenges faced by telephone surveys. Despite recent criticisms and the decline in response rates, their study reveals a special perspective against prevailing perceptions. Over the past two decades, an increase in bias has been documented; however, in a promising development, a downward trend has emerged in the last five years. It is observed that the inclusion of cell phone interviews significantly influences bias as a particular factor, highlighting the changing feature of survey methodologies. The study emphasizes the effectiveness of traditional weighting methods in mitigating linear trends in bias, which makes telephone samples as comparable in data quality to unweighted, in-person data, but also challenging the conceptions about their limitations despite higher response rates. This evaluation stimulates a reconsideration and reassessment of telephone data, challenging negative perceptions and illuminating its continued relevance in the future of survey research. The implications of these findings can be used by survey researchers. This research encourages a reconsideration of the role and effectiveness of telephone surveys in the broader context of survey research methodologies.
Dutwin and Buskirk's (2020) examination of contemporary telephone interviewing offers a perspective on the telephone surveys which are usually criticized. In an era where these surveys face skepticism due to election prediction failures and declining response rates, the study presents a crucial evaluation of the data quality derived from modern-day telephone interviewing. The research utilizes an elemental approach to assess bias of core demographics, drawing from surveys conducted in the past two decades. The findings reveal that: an increase in bias over the past two decades is countered by a promising downward trend in the last five years. This suggests that despite challenges, there is potential for improvement in data quality connected with telephone surveys. The impact of cell phone interviews on bias is a notable revelation, underscoring the evolving nature of survey methodologies and the need for adaptation. The study highlights the effectiveness of traditional weighting methods in mitigating linear bias trends, positioning telephone samples as comparable in data quality to unweighted, in-person data marked by higher response rates. These insights encourage a reconsideration of the prevailing skepticism surrounding telephone surveys, signaling a potential for adaptation within this survey methodology. The research contributes significantly to the future of survey research, urging practitioners and researchers to acknowledge the ongoing function in contemporary telephone interviewing.
To conclude, these papers collectively concentrate on the challenges coming from the declining response rates across diverse survey modes and emphasize the impact of telephone surveys. The studies by Williams and Brick (2018) and Dutwin and Buskirk (2020) offer distinct insights into survey research methodologies, focusing on face-to-face and telephone surveys, respectively. Williams and Brick illuminate historical trends in nonresponse in face-to-face household surveys, addressing a research gap and emphasizing the need to understand response rate changes in this methodology. The examination of survey efforts and their impact on response rates lays the foundation for future investigations. Dutwin and Buskirk challenge perceptions about declining data quality in telephone surveys, revealing a modest increase in bias countered by a promising downward trend in the last five years. The study highlights the potential for improving data quality, emphasizing the adaptability of telephone surveys, especially with cell phone inclusion. The effects of traditional weighting methods in mitigating bias trends makes telephone samples as comparable to in-person data with higher response rates. In general, these studies encourage a reconsideration of face-to-face and telephone survey methodologies, challenging negative perceptions and recognizing their relevance in the changing survey researches. The findings significantly contribute to the future of survey research, urging practitioners and researchers to acknowledge changes influencing response rates in diverse survey methodologies.

## Reference:
Olson, K & Thompson, K. Special Virtual Issue on Nonresponse Rates and Nonresponse Adjustments. Journal of Survey Statistics and Methodology. https://academic.oup.com/jssam/pages/special-virtual-issue-on-nonresponse-rates-and-nonresponse-adjustments?login=false. 
Williams, D. A., & Brick, J. M. (2018). Trends in U.S. Face-To-Face Household Survey Nonresponse and Level of Effort. Journal of Survey Statistics and Methodology, 6(2), 186–211. DOI: 10.1093/jssam/smx019.

Dutwin, D., & Buskirk, T. D. (2020). Telephone Sample Surveys: Dearly Beloved Nearly Departed? Trends in Survey Errors in the Era of Declining Response Rates. Journal of Survey Statistics and Methodology, 9(3), 353–380. DOI: 10.1093/jssam/smz044

Daikeler, J., Bošnjak, M., & Lozar Manfreda, K. (2020). Web Versus Other Survey Modes: Un Updated and Extended Meta-Analysis Comparing Response Rates. Journal of Survey Statistics and Methodology, 8(3), 513–539. DOI: 10.1093/jssam/smz008
